# Generated by Django 5.2.4 on 2025-12-15 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='講義名')),
                ('department', models.CharField(max_length=100, verbose_name='講義区分')),
                ('credits', models.IntegerField(verbose_name='単位数')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=100, verbose_name='講師名')),
                ('year', models.IntegerField()),
                ('day_of_week', models.IntegerField(choices=[(0, '月曜'), (1, '火曜'), (2, '水曜'), (3, '木曜'), (4, '金曜'), (5, '土曜'), (6, '日曜')], verbose_name='曜日')),
                ('period', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lecture_Search.course')),
            ],
        ),
    ]
