# Generated by Django 5.2.4 on 2025-12-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lecture_Search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, '月曜'), (1, '火曜'), (2, '水曜'), (3, '木曜'), (4, '金曜'), (5, '土曜')], verbose_name='曜日'),
        ),
    ]
