# Generated by Django 5.2.4 on 2025-12-31 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lecture_Search', '0002_alter_lecture_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='苗字')),
                ('first_name', models.CharField(max_length=100, verbose_name='名前')),
                ('full_name', models.CharField(max_length=200, verbose_name='フルネーム')),
            ],
        ),
        migrations.AlterField(
            model_name='lecture',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lecture_Search.instructor'),
        ),
    ]
